name: Build Game Image

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Publish Image
      uses: matootie/github-docker@v2.0.0
      env:
        sha: $GITHUB_SHA
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        imageTag: ${{ secrets.GITHUB_SHA }}
