name: Build Rhythm Game Image

on:
  push:
    branches:
    - master
  
  pull_request:
    branches:
    - master

env:
  IMAGE_NAME: rhythm-game

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker build . --file docker/Dockerfile --tag image
